// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DialogContent: typeof import('./src/components/naivePlugins/DialogContent/index.vue')['default']
    LoadingContent: typeof import('./src/components/naivePlugins/LoadingContent/index.vue')['default']
    MessageContent: typeof import('./src/components/naivePlugins/MessageContent/index.vue')['default']
    NaivePlugins: typeof import('./src/components/naivePlugins/index.vue')['default']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
